# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-12 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('cost_price', models.FloatField(verbose_name='cost price')),
                ('list_price', models.FloatField(verbose_name='list price')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
